# Generated by Django 2.0.4 on 2018-04-27 16:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32)),
                ('t_create', models.DateTimeField(auto_now_add=True)),
                ('t_modify', models.DateTimeField(auto_now=True)),
                ('t_delete', models.DateTimeField(blank=True, null=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True)),
                ('motto', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
            ],
            managers=[
                ('superuser', django.db.models.manager.Manager()),
            ],
        ),
    ]
