# Generated by Django 2.0.4 on 2018-04-28 17:52

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default='woshishei', max_length=64)),
                ('userUid', models.CharField(default='woshishei', max_length=64)),
                ('gmtCreate', models.DateTimeField(auto_now_add=True)),
                ('gmtModified', models.DateTimeField(auto_now=True)),
                ('gmtDelete', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='woshishei', max_length=64)),
                ('detail', models.CharField(default='woshishei', max_length=200)),
                ('isDelete', models.BooleanField(default=False)),
                ('status', models.IntegerField(default=0)),
            ],
            managers=[
                ('superuser', django.db.models.manager.Manager()),
            ],
        ),
    ]
